name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Poetry
      uses: actions/cache@v1
      env:
        cache-name: cache-poetry
      with: 
        path: ~/.poetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Cache pip
      uses: actions/cache@v1
      env:
        cache-name: cache-pip
      with: 
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

    - name: Poetry export requirements.txt
      run: ~/.poetry/bin/poetry export -f requirements.txt > requirements.txt

    - name: Build Docker Image
      run: |
        docker build -t github-action:latest .
        docker tag github-action:latest 083285518307.dkr.ecr.ap-northeast-2.amazonaws.com/github-action:latest

    - name: pytest
      run: docker run --rm github-action:latest coverage run --source='.' -m pytest app
      
    - name: Push DockerImage
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 083285518307.dkr.ecr.ap-northeast-2.amazonaws.com/github-action
        docker push 083285518307.dkr.ecr.ap-northeast-2.amazonaws.com/github-action:latest

    - name: ECS UpdateService
      run: aws ecs update-service --cluster GitHub-Action-Cluster --service GitHub-Action-Service
